+incdir+../ver_component/
+incdir+../ver_component/DUT/RTL/
+incdir+../ver_component/rm/RTL/
../ver_component/DUT/RTL/adder.sv
../ver_component/DUT/RTL/ALUdec.sv
../ver_component/DUT/RTL/ALU.sv
../ver_component/DUT/RTL/Control_Unit.sv
../ver_component/DUT/RTL/data_extend.sv
../ver_component/DUT/RTL/Data_Memory.sv
../ver_component/DUT/RTL/extend.sv
../ver_component/DUT/RTL/ff_D2E.sv
../ver_component/DUT/RTL/ff_E2M.sv
../ver_component/DUT/RTL/ff_F2D.sv
../ver_component/DUT/RTL/ff_M2W.sv
../ver_component/DUT/RTL/ff_pc.sv
../ver_component/DUT/RTL/Hazard_Unit.sv
../ver_component/DUT/RTL/imem.sv
../ver_component/DUT/RTL/mux2.sv
../ver_component/DUT/RTL/mux3.sv
../ver_component/DUT/RTL/mux_Branch.sv
../ver_component/DUT/RTL/mux_Result.sv
../ver_component/DUT/RTL/Register_File.sv
../ver_component/DUT/RTL/RISCV_TopLevel.sv
../ver_component/env_cfg.sv
../ver_component/environment.sv
../ver_component/pkt_chk.sv
../ver_component/pkt_data.sv
../ver_component/pkt_drv.sv
../ver_component/pkt_gen.sv
../ver_component/pkt_if_pack.sv
../ver_component/pkt_if.sv
../ver_component/pkt_mon.sv
../ver_component/rm/RTL/adder.sv
../ver_component/rm/RTL/ALUdec.sv
../ver_component/rm/RTL/ALU.sv
../ver_component/rm/RTL/Control_Unit.sv
../ver_component/rm/RTL/data_extend.sv
../ver_component/rm/RTL/Data_Memory.sv
../ver_component/rm/RTL/extend.sv
../ver_component/rm/RTL/ff_D2E.sv
../ver_component/rm/RTL/ff_E2M.sv
../ver_component/rm/RTL/ff_F2D.sv
../ver_component/rm/RTL/ff_M2W.sv
../ver_component/rm/RTL/ff_pc.sv
../ver_component/rm/RTL/Hazard_Unit.sv
../ver_component/rm/RTL/imem.sv
../ver_component/rm/RTL/mux2.sv
../ver_component/rm/RTL/mux3.sv
../ver_component/rm/RTL/mux_Branch.sv
../ver_component/rm/RTL/mux_Result.sv
../ver_component/rm/RTL/Register_File.sv
../ver_component/rm/RTL/riscv_core.sv
../ver_component/test.sv
../ver_component/top.sv
